// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiProducto;

#nullable disable

namespace WebApiProducto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiProducto.Entidades.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("WebApiProducto.Entidades.EmpresaProductos", b =>
                {
                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductosId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("EmpresaId", "ProductosId");

                    b.HasIndex("ProductosId");

                    b.ToTable("EmpresaProductos");
                });

            modelBuilder.Entity("WebApiProducto.Entidades.Opiniones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("productosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("productosId");

                    b.ToTable("Opiniones");
                });

            modelBuilder.Entity("WebApiProducto.Entidades.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("WebApiProducto.Entidades.EmpresaProductos", b =>
                {
                    b.HasOne("WebApiProducto.Entidades.Empresa", "Empresa")
                        .WithMany("EmpresasProductos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiProducto.Entidades.Productos", "Productos")
                        .WithMany("EmpresaProductos")
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("WebApiProducto.Entidades.Opiniones", b =>
                {
                    b.HasOne("WebApiProducto.Entidades.Productos", "Productos")
                        .WithMany("Opiniones")
                        .HasForeignKey("productosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("WebApiProducto.Entidades.Empresa", b =>
                {
                    b.Navigation("EmpresasProductos");
                });

            modelBuilder.Entity("WebApiProducto.Entidades.Productos", b =>
                {
                    b.Navigation("EmpresaProductos");

                    b.Navigation("Opiniones");
                });
#pragma warning restore 612, 618
        }
    }
}
